# Generated by Django 2.2.10 on 2020-06-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='topping_description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
