# Generated by Django 2.2.10 on 2020-06-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_orderitem_topping_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Preparing', 'Preparing'), ('Ready to collect', 'Ready to collect'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Received', max_length=64),
        ),
    ]
